import os
# Suppress TensorFlow logging to keep the terminal output clean
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
import cv2
import numpy as np

WEIGHTS_PATH = 'deepshield_trained_weights.weights.h5'


def build_cnn_architecture():
    """
    Builds the deepfake-detection model: a frozen, ImageNet-pretrained
    MobileNetV2 backbone (transfer learning) with a small trainable
    classification head on top.

    NOTE: this architecture must exactly match the one built in
    train_model.py's build_transfer_model() -- that's what produced the
    saved weights this function loads below. If you change one, change both.
    """
    print("[*] Initializing DeepShield CNN Architecture (MobileNetV2 transfer learning)...")

    base_model = tf.keras.applications.MobileNetV2(
        input_shape=(128, 128, 3),
        include_top=False,
        weights='imagenet',
    )
    base_model.trainable = False

    inputs = tf.keras.Input(shape=(128, 128, 3))
    x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs * 255.0)
    x = base_model(x, training=False)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dense(64, activation='relu')(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)

    model = tf.keras.Model(inputs, outputs)

    if os.path.exists(WEIGHTS_PATH):
        model.load_weights(WEIGHTS_PATH)
        print(f"[+] Loaded trained weights from '{WEIGHTS_PATH}'")
    else:
        print(f"[!] WARNING: '{WEIGHTS_PATH}' not found -- running with "
              f"UNTRAINED weights. Scores below are meaningless until you "
              f"run train_model.py first.")

    return model

def analyze_facial_media(image_path, cnn_model):
    """
    Preprocesses the extracted face and runs it through the CNN to generate a deepfake probability score. 
    """

    if not os.path.exists(image_path):
        print(f"[!] Error: Could not find '{image_path}'. Run face_detector.py first!!")
        return None
    
    print(f"[*] Loading extracted face into CNN: {image_path}")

    #step 1: Load the image
    image = cv2.imread(image_path)

    #step 2: Preprocessing: Resize to 128x128 pixels (what the CNN expects)
    resized_image = cv2.resize(image, (128, 128))

    #step 3: Preprocessing: Normalize pixel values to be between 0 and 1
    normalized_image= resized_image / 255.0

    #step 4: Reshaping for TensorFlow (Batch size of 1)
    input_data = np.expand_dims(normalized_image, axis=0)

    #step 5: Run the deepfake detection prediction
    print("[*] Analyzing texture inconsistencies and facial artifacts...")
    prediction = cnn_model.predict(input_data, verbose=0)

    #convert the raw output from decimal to percentage
    probability_score = float(prediction[0][0]) * 100

    return probability_score

#SIMULATION / PROTOTYPE TEST SCRIPT

if __name__ == "__main__":
    print("\n--- DeepShield: Deepfake Detection Engine (CNN) ---\n")
    
    # The file generated by Phase 3
    target_face = "extracted_face_for_CNN.jpg" 
    
    # Build the Neural Network
    model = build_cnn_architecture()
    
    # Analyze the face
    score = analyze_facial_media(target_face, model)
    
    if score is not None:
        print("\n    DETECTION RESULTS    ")
        print(f"Deepfake Probability Score: {score:.2f}%")
        
        if score > 70:
            print("Classification: [HIGH RISK - image most likely deepfake]")
        elif score > 30:
            print("Classification: [MEDIUM RISK - image may possibly be deepfake]")
        else:
            print("Classification: [LOW RISK - image most likely real]")
        print("                         \n")