import os
# Suppress TensorFlow logging to keep the terminal output clean
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
import cv2
import numpy as np

def build_cnn_architecture():
    """
    Builds the Convolutional Neural Network (CNN) architecture
    """
    print("[*] Initializing DeepShield CNN Architecture...")

    model = tf.keras.Sequential([
        #1st Convolutional Layer (Extracts basic facial features)
        tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(128, 128, 3)),
        tf.keras.layers.MaxPooling2D(2,2),

        #2nd Convolutional Layer (analyses texture inconsistencies/artifacts)
        tf.keras.layers.Conv2D(64, (3,3), activation='relu'), 
        tf.keras.layers.MaxPooling2D(2,2),

        #Flattening the data for the decision-making layers
        tf.keras.layers.Flatten(),

        #Dense decision layer
        tf.keras.layers.Dense(64, activation='relu'),

        #output layer (outputs a probability between 0.0 and 1.0)
        tf.keras.layers.Dense(1, activation = 'sigmoid')
    
    ])

    # In a full deployment, we would load the trained FaceForensics++ weights here:
    # model.load_weights('deepshield_trained_weights.h5')

    return model

def analyze_facial_media(image_path, cnn_model):
    """
    Preprocesses the extracted face and runs it through the CNN to generate a deepfake probability score. 
    """

    if not os.path.exists(image_path):
        print(f"[!] Error: Could not find '{image_path}'. Run face_detector.py first!!")
        return None
    
    print(f"[*] Loading extracted face into CNN: {image_path}")

    #step 1: Load the image
    image = cv2.imread(image_path)

    #step 2: Preprocessing: Resize to 128x128 pixels (what the CNN expects)
    resized_image = cv2.resize(image, (128, 128))

    #step 3: Preprocessing: Normalize pixel values to be between 0 and 1
    normalized_image= resized_image / 255.0

    #step 4: Reshaping for TensorFlow (Batch size of 1)
    input_data = np.expand_dims(normalized_image, axis=0)

    #step 5: Run the deepfake detection prediction
    print("[*] Analyzing texture inconsistencies and facial artifacts...")
    prediction = cnn_model.predict(input_data, verbose=0)

    #convert the raw output from decimal to percentage
    probability_score = float(prediction[0][0]) * 100

    return probability_score

#SIMULATION / PROTOTYPE TEST SCRIPT

if __name__ == "__main__":
    print("\n--- DeepShield: Deepfake Detection Engine (CNN) ---\n")
    
    # The file generated by Phase 3
    target_face = "extracted_face_for_CNN.jpg" 
    
    # Build the Neural Network
    model = build_cnn_architecture()
    
    # Analyze the face
    score = analyze_facial_media(target_face, model)
    
    if score is not None:
        print("\n    DETECTION RESULTS    ")
        print(f"Deepfake Probability Score: {score:.2f}%")
        
        if score > 70:
            print("Classification: [HIGH RISK - image most likely deepfake]")
        elif score > 30:
            print("Classification: [MEDIUM RISK - image may possibly be deepfake]")
        else:
            print("Classification: [LOW RISK - image most likely real]")
        print("                         \n")